name: pipeline liner
on: 
  push:
    branches:
      - main
  
  pull-request:
    branches:
      - main 

jobs: 
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      uses: actions/checkout@v2

      - name: User Node.js
      uses: actions/setup-node@v2
      with:
        node-version:'20.14'

      - name: install dependency
      run: npm install

      - name: Run liner
      run: npm run lint

